config/routes.rb
SeatYourself::Application.routes.draw do

	resources :sessions, :only=>[:new, :create, :destroy]
  
  resources :users, :except=>[:index] do
  	get 'profile', on: :collection, as: "profile"
  end

  resources :restaurants do
  	resources :reservations, :except=>[:index]	
  end

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :user

	
	#validate :date
	validate :not_in_past
	validate :availability

	validates :party_size, :presence=>true, :numericality => {:only_integer=>true}
	

	private
	def availability
		if !restaurant.availability(party_size, party_time)
			errors.add(:base, "Sorry, restaurant is full for your party-size")
		end
	end


	def date
		t = party_time
		expectation = (t.month!="month" && t.day!="day" && t.hour!="hour")
		if !expectation
			errors.add(:base, "Please double check your reservation date and time")
		end
	end

	def not_in_past
		t = party_time
		n = DateTime.now
		expectation = (t.month >= n.month)
		
		if t.month == n.month
				expectation = t.day >= n.day
		end
	

		if !expectation
			errors.add(:base, "This reservation is in the past #{t.year}")
		end
	end


end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reservations
	has_many :users, :through => :reservations	

	

	def availability(party_size, party_time)
		#reserve_size = reservations.where("party_time = ?", party_time).sum(:party_size)
		reserve_size = reservations_at(party_time)
		reserve_size + party_size <= capacity
	end

	def reservations_at(party_time)
		reservations.where("party_time = ?", party_time).sum(:party_size)
	end

	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :reservations
	has_many :restaurants, through: :reservations

	validates :name, presence: [:true]
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }
	validates :telephone, presence: [:true], :numericality=>{:only_integer=>:true}, length: { :maximum=>10 }
	validates :user_type, presence: [:true], :numericality=>{:only_integer=>:true, :message=>" - please select an account type"}
	


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end

  def ensure_owner
    unless current_user && current_user.user_type==2
      flash[:alert] = "You must have an owner account to create a new restaurant"
      redirect_to restaurants_path
    end
  end

  helper_method :current_user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_filter :load_restaurant
  before_filter :ensure_logged_in
  
  def show
  	@reservation = Reservation.find(params[:id])
  end

  def new
  	@reservation = Reservation.new
  end

  def create
  	@reservation = @restaurant.reservations.build(reservation_params)
  	@reservation.user_id = current_user.id

  	if @reservation.save
      redirect_to profile_users_path, :notice=>"Reservation made!!!"
    else
  		render :new
  	end
  end


  def edit
    @reservation = Reservation.find(params[:id])
  end

	def update
    @reservation = Reservation.find(params[:id])

    if @reservation.update_attributes(reservation_params)
      redirect_to profile_users_path
    else
      render :edit
    end
	end  

	def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to profile_users_path
	end

	private
	def reservation_params
		params.require(:reservation).permit(:party_size, :party_time)
	end

	def load_restaurant
		@restaurant = Restaurant.find(params[:restaurant_id])
	end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_filter :ensure_logged_in, :except=>[:index]
  before_filter :ensure_owner, :except=>[:index]

  def index
  	@restaurants = Restaurant.all
  end

  def show
  	@restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.update_attributes(restaurant_params)
  end


  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :capacity)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to restaurants_url, :notice=>"Logged in!"
  	else
  		flash.now[:alert] = "Invalid email or password"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to restaurants_url, :notice=>"Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :load_restaurants 
  before_filter :ensure_logged_in, :only=>[:profile]
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
  		redirect_to restaurants_url, :notice=>"Signed Up!"
  	else
  		render "new"
  	end
  end

  
  def profile
    @user = current_user
  end

  private

  def user_params
  	params.require(:user).permit(:user_type, :name, :telephone, :email, :password, :password_confirmation)
  end

  def load_restaurants
    @restaurant = Restaurant.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  		<% if flash[:notice] %>
				<p id="notice"><%= flash[:notice] %></p>
			<% end %>	
			<% if flash[:alert] %>
				<p id="alert"><%= flash[:alert] %></p>
			<% end %>

			<p class="userinfo">
				<% if current_user %>
					Signed in as: <%= current_user.name %>.  <%= link_to "Log Out", session_path("current"), :method=>:delete %>
				<% else %>
					<%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
				<% end %>
			</p>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_for([@restaurant, @reservation]) do |f| %>
	<% if @reservation.errors.any? %>
		<div class="error_messages">
			<h3>mmmm....sorry</h3>
			<ul>
				<% @reservation.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		At: <%= f.label @restaurant.name %><br/><br/>
	</div>
	<div class="field">
		<%= f.label :party_size %><br/>
		<%= f.text_field :party_size %>
	</div>
	<div class="field">
		<%= f.label :party_time %><br/>
		<%= f.datetime_select(:party_time, order: [:year, :month, :day, :hour], prompt:{month:"month", day:"day", hour:"hour"}, discard_minute: true, start_year: 2014 )%>
	</div>
	<div class="submit">
		<%= f.submit %>
	</div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Edit Reservation</h1>

<%= render 'form' %>

app/views/reservations/new.html.erb
<h2>Make a Reservation</h2>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
	<% if @restaurant.errors.any? %>
		<div class="error_messages">
			<h3>Errors were found:</h3>
				<ul>
					<%= @restaurant.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_field :description %>
	</div>
	<div class="field">
		<%= f.label :capacity %>
		<%= f.text_field :capacity %>
	</div>
	<div class="field">
		<%= f.submit %>
	</div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<div class="main_container">
	<% @restaurants.each do |restaurant| %>
		<div class="restaurant">
			<span class="title"><%= link_to restaurant.name, restaurant_path(restaurant)%></span> - <%= restaurant.description %>

		</div>
	<% end %>
</div>

app/views/restaurants/new.html.erb
<h1>Create Restaurant</h1>



<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1>Close Up</h1>
<div class="restaurant">
	<span class="title"><%= @restaurant.name %></span><br/>
	<%= @restaurant.description %>
	<%= link_to "Make Reservation", new_restaurant_reservation_path(@restaurant) %>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h2>Sign Up - The More; The Merrier</h2>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h3>mmmm....sorry</h3>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :user_type, "User Type" %>
			<%= f.select :user_type, [["Select"],["Patron", 1],["Owner", 2]] %>
	</div>
	<div class="field">
		<%= f.label :name %><br/>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :telephone %><br/>
		<%= f.text_field :telephone %>
	</div>
	<div class="field">
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br/>
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation %><br/>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit " Send " %>
	</div>
<% end %>

app/views/users/profile.html.erb
<h1>My Reservations</h1>
<div class="reservations">
	<% @user.reservations.each do |reservation| %>
		<p><span class="title"><%= @restaurant.find(reservation.restaurant_id).name %></span> - 
			<% 
				m = reservation.party_time.month
				d = reservation.party_time.day
				h = reservation.party_time.hour
				t = reservation.party_time
			%>
			<%= t.strftime("%b %d, %l%P") %><br/>
			<%= "Party of: #{reservation.party_size} people" %>
			<%= link_to 'Edit', edit_restaurant_reservation_path(reservation.restaurant, reservation) %>
			<%= link_to 'Delete', restaurant_reservation_path(reservation.restaurant, reservation), :confirm=>"Are you sure you want to delete this reservation?", :method=>:delete %>
		</p>
	<% end %>
</div>